version: '3'

services:
    server:
        build:
            context: '../server'
        container_name: to2-server
        restart: 'always'
        ports:
            - '13000:13000'
        environment:
            - MOONGO_CONNECTION_STRING=
            - JWT_TOKEN=
            - PORT=13000
            - BASE_URL=https://to2api.sammyshehter.com
            - RICK_URL=https://www.youtube.com/watch?v=dQw4w9WgXcQ

    client:
        build:
            context: '../client'
        container_name: to2-client
        depends_on:
            - server
        restart: 'always'
        ports:
            - '14000:80'
