version: '3'

services:
    server:
        build:
            context: '../server'
        container_name: to2-server
        restart: 'always'
        ports:
            - '13000:13000'
    client:
        build:
            context: '../client'
        container_name: to2-client
        depends_on:
            - server
        restart: 'always'
        ports:
            - '14000:80'
