version: '3'

services:
    server:
        build:
            context: '../server'
        container_name: to2-server
        restart: 'always'
        ports:
            - '13000:13000'
        environment:
            - MOONGO_CONNECTION_STRING=mongodb+srv://worker:xEJMkgYK1xReH52cg@mufinfo.rdfjw.mongodb.net/T02?retryWrites=true&w=majority
            - JWT_TOKEN=xx/@k:!cvHD"n&gN3yp^GVqb&k^\el194!
            - PORT=13000
            - BASE_URL=http://localhost:13000
            - RICK_URL=https://www.youtube.com/watch?v=dQw4w9WgXcQ

    client:
        build:
            context: '../client'
        container_name: to2-client
        depends_on:
            - server
        restart: 'always'
        ports:
            - '14000:80'
